### ISSUE TITLE
User can receive transcribed audio from watson.

### ISSUE THREAD

**Issue by Robert-Jung** [Robert-Jung/SpeakEZ#3]
![image](https://cloud.githubusercontent.com/assets/22306788/25051050/8dd1de04-20ff-11e7-8858-de80d8291607.png)

- [x] Conver audio blob to audio.wav using 'fluent-ffmpeg' library'
- [x] Send uploaded audio.wav file to Watson Api to be transcribed.
- [x] Transcribed text will be saved in txt file "transcription.txt"
- [x] Append transcribed text to browser

**Comment by victormejia** [comment]
I'm assuming from the UI the user will be able to see the transcribed audio? If so, let's get some sort of wireframe here...
