### ISSUE TITLE
User can search inventory using voice

### ISSUE THREAD

**Issue by Robert-Jung** [Robert-Jung/SpeakEZ#7]
![image](https://cloud.githubusercontent.com/assets/22306788/25104447/38f29964-2375-11e7-91a6-ad1efc1b17e9.png)

- [x] Create in-memory array.
- [x] User can see "inventory array" on DOM
- [x] User can search product name in array using keyword "search"
- [x] User can return information for product by searching "upc" from array.
- [x] Create table and append search results on DOM.

**Comment by victormejia** [comment]
As discussed, let's hold off on the persistence layer and use an in-memory array for now.

**Comment by Robert-Jung** [comment]
![search_example](https://cloud.githubusercontent.com/assets/22306788/26331801/bbfcb7e2-3f07-11e7-9f97-d825edb8f50d.gif)
